services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=kingmojang'
      - 'MYSQL_PASSWORD=password'
      - 'MYSQL_ROOT_PASSWORD=password'
      - 'MYSQL_USER=soko'
    ports:
      - '3306:3306'
