services:
  mysql:
    image: 'mysql:latest'
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--character-set-filesystem=utf8mb4"
      # - "--default-time-zone='+09:00'"
      - "--max_connections=100"
      - "--max_connect_errors=999999"

      - "--innodb_sort_buffer_size=5M"

      - "--innodb_log_files_in_group=2"
      - "--innodb_log_file_size=1024M"

      - "--innodb_buffer_pool_size=200M"
      - "--innodb_buffer_pool_instances=1"
      - "--innodb_io_capacity=100"
      - "--innodb_io_capacity_max=400"

      - "--slow-query-log=1"
      - "--long_query_time=1"
      - "--log_slow_extra=1"
      - "--log_slow_admin_statements=1"
      - "--log_slow_slave_statements=1"

      - "--binlog_expire_logs_seconds=258200"
      - "--log-raw"
      - "--log_timestamps=SYSTEM"
    environment:
      - 'MYSQL_DATABASE=kingmojang'
      - 'MYSQL_PASSWORD=password'
      - 'MYSQL_ROOT_PASSWORD=password'
      - 'MYSQL_USER=soko'
    ports:
      - '3306:3306'
