spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kingmojang?useSSL=false&serverTimezone=UTC
    username: soko
    password: password

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    open-in-view: false
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  docker:
    compose:
      enabled: true

logging:
  level:
    root: debug

log:
  config:
    filename: app-dev
    maxHistory: 7
    maxFileSize: 50MB
    totalSizeCap: 1GB